PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP   TABLE IF     EXISTS K;
CREATE TABLE IF NOT EXISTS K(
    KEY INTEGER  NOT NULL,
    VAL INTEGER
);

INSERT INTO K VALUES(1,77);
INSERT INTO K VALUES(2,4);
INSERT INTO K VALUES(3,2);
INSERT INTO K VALUES(4,293);
INSERT INTO K VALUES(5,223);

COMMIT;

