PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP   TABLE IF     EXISTS M;
CREATE TABLE IF NOT EXISTS M(
    MediaTypeId INTEGER  NOT NULL,
    Name NVARCHAR(120),
    CONSTRAINT PK_MediaType PRIMARY KEY  (MediaTypeId)
);
INSERT INTO M VALUES(1,'MPEG audio file');
INSERT INTO M VALUES(2,'Protected AAC audio file');
INSERT INTO M VALUES(3,'Protected MPEG-4 video file');
INSERT INTO M VALUES(4,'Purchased AAC audio file');
INSERT INTO M VALUES(5,'AAC audio file');

COMMIT;
