PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP   TABLE IF     EXISTS P;
CREATE TABLE IF NOT EXISTS P(
    PlaylistId INTEGER  NOT NULL,
    Name NVARCHAR(120),
    CONSTRAINT PK_Playlist PRIMARY KEY  (PlaylistId)
);
INSERT INTO P VALUES(1,'Movies');
INSERT INTO P VALUES(2,'TV Shows');
INSERT INTO P VALUES(3,'Books');
INSERT INTO P VALUES(4,'Tabes');
INSERT INTO P VALUES(5,'Next_G');

COMMIT;
